schema_version = "1.0.0"

id = "imeshh"
version = "1.2.4"
name = "iMeshh"
tagline = "iMeshh Assets Library"
maintainer = "iMeshh, Karan @b3dhub"
type = "add-on"
website = "http://imeshh.com"
tags = [
    "Pipeline",
    "3D View",
    "Add Mesh",
    "Lighting",
    "Material",
    "Modeling",
    "Mesh",
    "Node",
    "Object",
    "Pipeline",
    "Render",
    "Scene",
    "System",
    "User Interface",
    "UV",
]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
permissions.network = "Accessing iMeshh API and downloading assets"
permissions.files = "Load and save blend files from disk"
permissions.clipboard = "Copy and paste error logs"
copyright = ["2025 iMeshh"]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=macosx_11_0_arm64
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=manylinux_2_28_x86_64
# pip download pillow --dest ./wheels --only-binary=:all: --python-version=3.11 --platform=win_amd64
wheels = [
    "./wheels/t3dn_bip-1.0.11-py3-none-any.whl",
    "./wheels/PyJWT-2.10.1-py3-none-any.whl",
    "./wheels/pillow-11.1.0-cp311-cp311-win_amd64.whl",
    "./wheels/pillow-11.1.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pillow-11.1.0-cp311-cp311-manylinux_2_28_x86_64.whl",
]
