from . import _base

class BEventType(_base.BStaticEnum):

	NONE = dict(n='NONE', d='NONE')
	LEFTMOUSE = dict(n='Left Mouse', d='LMB')
	MIDDLEMOUSE = dict(n='Middle Mouse', d='MMB')
	RIGHTMOUSE = dict(n='Right Mouse', d='RMB')
	BUTTON4MOUSE = dict(n='Button4 Mouse', d='MB4')
	BUTTON5MOUSE = dict(n='Button5 Mouse', d='MB5')
	BUTTON6MOUSE = dict(n='Button6 Mouse', d='MB6')
	BUTTON7MOUSE = dict(n='Button7 Mouse', d='MB7')
	PEN = dict(n='Pen', d='Pen')
	ERASER = dict(n='Eraser', d='Eraser')
	MOUSEMOVE = dict(n='Mouse Move', d='MsMov')
	INBETWEEN_MOUSEMOVE = dict(n='In-between Move', d='MsSubMov')
	TRACKPADPAN = dict(n='Mouse/Trackpad Pan', d='MsPan')
	TRACKPADZOOM = dict(n='Mouse/Trackpad Zoom', d='MsZoom')
	MOUSEROTATE = dict(n='Mouse/Trackpad Rotate', d='MsRot')
	MOUSESMARTZOOM = dict(n='Mouse/Trackpad Smart Zoom', d='MsSmartZoom')
	WHEELUPMOUSE = dict(n='Wheel Up', d='WhUp')
	WHEELDOWNMOUSE = dict(n='Wheel Down', d='WhDown')
	WHEELINMOUSE = dict(n='Wheel In', d='WhIn')
	WHEELOUTMOUSE = dict(n='Wheel Out', d='WhOut')
	A = dict(n='A', d='A')
	B = dict(n='B', d='B')
	C = dict(n='C', d='C')
	D = dict(n='D', d='D')
	E = dict(n='E', d='E')
	F = dict(n='F', d='F')
	G = dict(n='G', d='G')
	H = dict(n='H', d='H')
	I = dict(n='I', d='I')
	J = dict(n='J', d='J')
	K = dict(n='K', d='K')
	L = dict(n='L', d='L')
	M = dict(n='M', d='M')
	N = dict(n='N', d='N')
	O = dict(n='O', d='O')
	P = dict(n='P', d='P')
	Q = dict(n='Q', d='Q')
	R = dict(n='R', d='R')
	S = dict(n='S', d='S')
	T = dict(n='T', d='T')
	U = dict(n='U', d='U')
	V = dict(n='V', d='V')
	W = dict(n='W', d='W')
	X = dict(n='X', d='X')
	Y = dict(n='Y', d='Y')
	Z = dict(n='Z', d='Z')
	ZERO = dict(n='ZERO', d='ZERO')
	ONE = dict(n='ONE', d='ONE')
	TWO = dict(n='TWO', d='TWO')
	THREE = dict(n='THREE', d='THREE')
	FOUR = dict(n='FOUR', d='FOUR')
	FIVE = dict(n='FIVE', d='FIVE')
	SIX = dict(n='SIX', d='SIX')
	SEVEN = dict(n='SEVEN', d='SEVEN')
	EIGHT = dict(n='EIGHT', d='EIGHT')
	NINE = dict(n='NINE', d='NINE')
	LEFT_CTRL = dict(n='Left Ctrl', d='CtrlL')
	LEFT_ALT = dict(n='Left Alt', d='AltL')
	LEFT_SHIFT = dict(n='Left Shift', d='ShiftL')
	RIGHT_ALT = dict(n='Right Alt', d='AltR')
	RIGHT_CTRL = dict(n='Right Ctrl', d='CtrlR')
	RIGHT_SHIFT = dict(n='Right Shift', d='ShiftR')
	OSKEY = dict(n='OS Key', d='Cmd')
	APP = dict(n='Application', d='App')
	GRLESS = dict(n='Grless', d='Grless')
	ESC = dict(n='Esc', d='Esc')
	TAB = dict(n='Tab', d='Tab')
	RET = dict(n='Return', d='Enter')
	SPACE = dict(n='Spacebar', d='Space')
	LINE_FEED = dict(n='Line Feed', d='Line Feed')
	BACK_SPACE = dict(n='Backspace', d='BkSpace')
	DEL = dict(n='Delete', d='Del')
	SEMI_COLON = dict(n=';', d=';')
	PERIOD = dict(n='PERIOD', d='PERIOD')
	COMMA = dict(n=',', d=',')
	QUOTE = dict(n='“', d='“')
	ACCENT_GRAVE = dict(n='`', d='`')
	MINUS = dict(n='-', d='-')
	PLUS = dict(n='+', d='+')
	SLASH = dict(n='/', d='/')
	BACK_SLASH = dict(n='\\', d='\\')
	EQUAL = dict(n='=', d='=')
	LEFT_BRACKET = dict(n='[', d='[')
	RIGHT_BRACKET = dict(n=']', d=']')
	LEFT_ARROW = dict(n='Left Arrow', d='←')
	DOWN_ARROW = dict(n='Down Arrow', d='↓')
	RIGHT_ARROW = dict(n='Right Arrow', d='→')
	UP_ARROW = dict(n='Up Arrow', d='↑')
	NUMPAD_2 = dict(n='Numpad 2', d='Pad2')
	NUMPAD_4 = dict(n='Numpad 4', d='Pad4')
	NUMPAD_6 = dict(n='Numpad 6', d='Pad6')
	NUMPAD_8 = dict(n='Numpad 8', d='Pad8')
	NUMPAD_1 = dict(n='Numpad 1', d='Pad1')
	NUMPAD_3 = dict(n='Numpad 3', d='Pad3')
	NUMPAD_5 = dict(n='Numpad 5', d='Pad5')
	NUMPAD_7 = dict(n='Numpad 7', d='Pad7')
	NUMPAD_9 = dict(n='Numpad 9', d='Pad9')
	NUMPAD_PERIOD = dict(n='Numpad .', d='Pad.')
	NUMPAD_SLASH = dict(n='Numpad /', d='Pad/')
	NUMPAD_ASTERIX = dict(n='Numpad *', d='Pad*')
	NUMPAD_0 = dict(n='Numpad 0', d='Pad0')
	NUMPAD_MINUS = dict(n='Numpad -', d='Pad-')
	NUMPAD_ENTER = dict(n='Numpad Enter', d='PadEnter')
	NUMPAD_PLUS = dict(n='Numpad +', d='Pad+')
	F1 = dict(n='F1', d='F1')
	F2 = dict(n='F2', d='F2')
	F3 = dict(n='F3', d='F3')
	F4 = dict(n='F4', d='F4')
	F5 = dict(n='F5', d='F5')
	F6 = dict(n='F6', d='F6')
	F7 = dict(n='F7', d='F7')
	F8 = dict(n='F8', d='F8')
	F9 = dict(n='F9', d='F9')
	F10 = dict(n='F10', d='F10')
	F11 = dict(n='F11', d='F11')
	F12 = dict(n='F12', d='F12')
	F13 = dict(n='F13', d='F13')
	F14 = dict(n='F14', d='F14')
	F15 = dict(n='F15', d='F15')
	F16 = dict(n='F16', d='F16')
	F17 = dict(n='F17', d='F17')
	F18 = dict(n='F18', d='F18')
	F19 = dict(n='F19', d='F19')
	F20 = dict(n='F20', d='F20')
	F21 = dict(n='F21', d='F21')
	F22 = dict(n='F22', d='F22')
	F23 = dict(n='F23', d='F23')
	F24 = dict(n='F24', d='F24')
	PAUSE = dict(n='Pause', d='Pause')
	INSERT = dict(n='Insert', d='Ins')
	HOME = dict(n='Home', d='Home')
	PAGE_UP = dict(n='Page Up', d='PgUp')
	PAGE_DOWN = dict(n='Page Down', d='PgDown')
	END = dict(n='End', d='End')
	MEDIA_PLAY = dict(n='Media Play/Pause', d='>/||')
	MEDIA_STOP = dict(n='Media Stop', d='Stop')
	MEDIA_FIRST = dict(n='Media First', d='|<<')
	MEDIA_LAST = dict(n='Media Last', d='>>|')
	TEXTINPUT = dict(n='Text Input', d='TxtIn')
	WINDOW_DEACTIVATE = dict(n='Window Deactivate', d='Window Deactivate')
	TIMER = dict(n='Timer', d='Tmr')
	TIMER0 = dict(n='Timer 0', d='Tmr0')
	TIMER1 = dict(n='Timer 1', d='Tmr1')
	TIMER2 = dict(n='Timer 2', d='Tmr2')
	TIMER_JOBS = dict(n='Timer Jobs', d='TmrJob')
	TIMER_AUTOSAVE = dict(n='Timer Autosave', d='TmrSave')
	TIMER_REPORT = dict(n='Timer Report', d='TmrReport')
	TIMERREGION = dict(n='Timer Region', d='TmrReg')
	NDOF_MOTION = dict(n='NDOF Motion', d='NdofMov')
	NDOF_BUTTON_MENU = dict(n='NDOF Menu', d='NdofMenu')
	NDOF_BUTTON_FIT = dict(n='NDOF Fit', d='NdofFit')
	NDOF_BUTTON_TOP = dict(n='NDOF Top', d='Ndof↑')
	NDOF_BUTTON_BOTTOM = dict(n='NDOF Bottom', d='Ndof↓')
	NDOF_BUTTON_LEFT = dict(n='NDOF Left', d='Ndof←')
	NDOF_BUTTON_RIGHT = dict(n='NDOF Right', d='Ndof→')
	NDOF_BUTTON_FRONT = dict(n='NDOF Front', d='NdofFront')
	NDOF_BUTTON_BACK = dict(n='NDOF Back', d='NdofBack')
	NDOF_BUTTON_ISO1 = dict(n='NDOF Isometric 1', d='NdofIso1')
	NDOF_BUTTON_ISO2 = dict(n='NDOF Isometric 2', d='NdofIso2')
	NDOF_BUTTON_ROLL_CW = dict(n='NDOF Roll CW', d='NdofRCW')
	NDOF_BUTTON_ROLL_CCW = dict(n='NDOF Roll CCW', d='NdofRCCW')
	NDOF_BUTTON_SPIN_CW = dict(n='NDOF Spin CW', d='NdofSCW')
	NDOF_BUTTON_SPIN_CCW = dict(n='NDOF Spin CCW', d='NdofSCCW')
	NDOF_BUTTON_TILT_CW = dict(n='NDOF Tilt CW', d='NdofTCW')
	NDOF_BUTTON_TILT_CCW = dict(n='NDOF Tilt CCW', d='NdofTCCW')
	NDOF_BUTTON_ROTATE = dict(n='NDOF Rotate', d='NdofRot')
	NDOF_BUTTON_PANZOOM = dict(n='NDOF Pan/Zoom', d='NdofPanZoom')
	NDOF_BUTTON_DOMINANT = dict(n='NDOF Dominant', d='NdofDom')
	NDOF_BUTTON_PLUS = dict(n='NDOF Plus', d='Ndof+')
	NDOF_BUTTON_MINUS = dict(n='NDOF Minus', d='Ndof-')
	NDOF_BUTTON_V1 = dict(n='NDOF View 1', d='NDOF View 1')
	NDOF_BUTTON_V2 = dict(n='NDOF View 2', d='NDOF View 2')
	NDOF_BUTTON_V3 = dict(n='NDOF View 3', d='NDOF View 3')
	NDOF_BUTTON_1 = dict(n='NDOF Button 1', d='NdofB1')
	NDOF_BUTTON_2 = dict(n='NDOF Button 2', d='NdofB2')
	NDOF_BUTTON_3 = dict(n='NDOF Button 3', d='NdofB3')
	NDOF_BUTTON_4 = dict(n='NDOF Button 4', d='NdofB4')
	NDOF_BUTTON_5 = dict(n='NDOF Button 5', d='NdofB5')
	NDOF_BUTTON_6 = dict(n='NDOF Button 6', d='NdofB6')
	NDOF_BUTTON_7 = dict(n='NDOF Button 7', d='NdofB7')
	NDOF_BUTTON_8 = dict(n='NDOF Button 8', d='NdofB8')
	NDOF_BUTTON_9 = dict(n='NDOF Button 9', d='NdofB9')
	NDOF_BUTTON_10 = dict(n='NDOF Button 10', d='NdofB10')
	NDOF_BUTTON_A = dict(n='NDOF Button A', d='NdofBA')
	NDOF_BUTTON_B = dict(n='NDOF Button B', d='NdofBB')
	NDOF_BUTTON_C = dict(n='NDOF Button C', d='NdofBC')
	ACTIONZONE_AREA = dict(n='ActionZone Area', d='AZone Area')
	ACTIONZONE_REGION = dict(n='ActionZone Region', d='AZone Region')
	ACTIONZONE_FULLSCREEN = dict(n='ActionZone Fullscreen', d='AZone FullScr')
	XR_ACTION = dict(n='XR Action', d='XR Action')
