from . import _base

class BIDType(_base.BStaticEnum):

	ACTION = dict(n='Action', d='Action')
	ARMATURE = dict(n='Armature', d='Armature')
	BRUSH = dict(n='Brush', d='Brush')
	CACHEFILE = dict(n='Cache File', d='Cache File')
	CAMERA = dict(n='Camera', d='Camera')
	COLLECTION = dict(n='Collection', d='Collection')
	CURVE = dict(n='Curve', d='Curve')
	CURVES = dict(n='Curves', d='Curves')
	FONT = dict(n='Font', d='Font')
	GREASEPENCIL = dict(n='Grease Pencil', d='Grease Pencil')
	IMAGE = dict(n='Image', d='Image')
	KEY = dict(n='Key', d='Key')
	LATTICE = dict(n='Lattice', d='Lattice')
	LIBRARY = dict(n='Library', d='Library')
	LIGHT = dict(n='Light', d='Light')
	LIGHT_PROBE = dict(n='Light Probe', d='Light Probe')
	LINESTYLE = dict(n='Line Style', d='Line Style')
	MASK = dict(n='Mask', d='Mask')
	MATERIAL = dict(n='Material', d='Material')
	MESH = dict(n='Mesh', d='Mesh')
	META = dict(n='Metaball', d='Metaball')
	MOVIECLIP = dict(n='Movie Clip', d='Movie Clip')
	NODETREE = dict(n='Node Tree', d='Node Tree')
	OBJECT = dict(n='Object', d='Object')
	PAINTCURVE = dict(n='Paint Curve', d='Paint Curve')
	PALETTE = dict(n='Palette', d='Palette')
	PARTICLE = dict(n='Particle', d='Particle')
	POINTCLOUD = dict(n='Point Cloud', d='Point Cloud')
	SCENE = dict(n='Scene', d='Scene')
	SIMULATION = dict(n='Simulation', d='Simulation')
	SOUND = dict(n='Sound', d='Sound')
	SPEAKER = dict(n='Speaker', d='Speaker')
	TEXT = dict(n='Text', d='Text')
	TEXTURE = dict(n='Texture', d='Texture')
	VOLUME = dict(n='Volume', d='Volume')
	WINDOWMANAGER = dict(n='Window Manager', d='Window Manager')
	WORKSPACE = dict(n='Workspace', d='Workspace')
	WORLD = dict(n='World', d='World')
