from . import _base

class BPropertySubtype(_base.BStaticEnum):

	NONE = dict(n='None', d='None')
	FILE_PATH = dict(n='File Path', d='File Path')
	DIR_PATH = dict(n='Directory Path', d='Directory Path')
	FILE_NAME = dict(n='File Name', d='File Name')
	BYTE_STRING = dict(n='Byte String', d='Byte String')
	PASSWORD = dict(n='Password', d='A string that is displayed hidden (’********’)')
	PIXEL = dict(n='Pixel', d='Pixel')
	UNSIGNED = dict(n='Unsigned', d='Unsigned')
	PERCENTAGE = dict(n='Percentage', d='Percentage')
	FACTOR = dict(n='Factor', d='Factor')
	ANGLE = dict(n='Angle', d='Angle')
	TIME = dict(n='Time (Scene Relative)', d='Time specified in frames, converted to seconds based on scene frame rate')
	TIME_ABSOLUTE = dict(n='Time (Absolute)', d='Time specified in seconds, independent of the scene')
	DISTANCE = dict(n='Distance', d='Distance')
	DISTANCE_CAMERA = dict(n='Camera Distance', d='Camera Distance')
	POWER = dict(n='Power', d='Power')
	TEMPERATURE = dict(n='Temperature', d='Temperature')
	COLOR = dict(n='Color', d='Color')
	TRANSLATION = dict(n='Translation', d='Translation')
	DIRECTION = dict(n='Direction', d='Direction')
	VELOCITY = dict(n='Velocity', d='Velocity')
	ACCELERATION = dict(n='Acceleration', d='Acceleration')
	MATRIX = dict(n='Matrix', d='Matrix')
	EULER = dict(n='Euler Angles', d='Euler Angles')
	QUATERNION = dict(n='Quaternion', d='Quaternion')
	AXISANGLE = dict(n='Axis-Angle', d='Axis-Angle')
	XYZ = dict(n='XYZ', d='XYZ')
	XYZ_LENGTH = dict(n='XYZ Length', d='XYZ Length')
	COLOR_GAMMA = dict(n='Color', d='Color')
	COORDINATES = dict(n='Coordinates', d='Coordinates')
	LAYER = dict(n='Layer', d='Layer')
	LAYER_MEMBER = dict(n='Layer Member', d='Layer Member')
