from . import _base

class BTransformModeTypes(_base.BStaticEnum):

	INIT = dict(n='Init', d='Init')
	DUMMY = dict(n='Dummy', d='Dummy')
	TRANSLATION = dict(n='Translation', d='Translation')
	ROTATION = dict(n='Rotation', d='Rotation')
	RESIZE = dict(n='Resize', d='Resize')
	SKIN_RESIZE = dict(n='Skin Resize', d='Skin Resize')
	TOSPHERE = dict(n='To Sphere', d='To Sphere')
	SHEAR = dict(n='Shear', d='Shear')
	BEND = dict(n='Bend', d='Bend')
	SHRINKFATTEN = dict(n='Shrink/Fatten', d='Shrink/Fatten')
	TILT = dict(n='Tilt', d='Tilt')
	TRACKBALL = dict(n='Trackball', d='Trackball')
	PUSHPULL = dict(n='Push/Pull', d='Push/Pull')
	CREASE = dict(n='Crease', d='Crease')
	VERTEX_CREASE = dict(n='Vertex Crease', d='Vertex Crease')
	MIRROR = dict(n='Mirror', d='Mirror')
	BONE_SIZE = dict(n='Bone Size', d='Bone Size')
	BONE_ENVELOPE = dict(n='Bone Envelope', d='Bone Envelope')
	BONE_ENVELOPE_DIST = dict(n='Bone Envelope Distance', d='Bone Envelope Distance')
	CURVE_SHRINKFATTEN = dict(n='Curve Shrink/Fatten', d='Curve Shrink/Fatten')
	MASK_SHRINKFATTEN = dict(n='Mask Shrink/Fatten', d='Mask Shrink/Fatten')
	GPENCIL_SHRINKFATTEN = dict(n='Grease Pencil Shrink/Fatten', d='Grease Pencil Shrink/Fatten')
	BONE_ROLL = dict(n='Bone Roll', d='Bone Roll')
	TIME_TRANSLATE = dict(n='Time Translate', d='Time Translate')
	TIME_SLIDE = dict(n='Time Slide', d='Time Slide')
	TIME_SCALE = dict(n='Time Scale', d='Time Scale')
	TIME_EXTEND = dict(n='Time Extend', d='Time Extend')
	BAKE_TIME = dict(n='Bake Time', d='Bake Time')
	BWEIGHT = dict(n='Bevel Weight', d='Bevel Weight')
	ALIGN = dict(n='Align', d='Align')
	EDGESLIDE = dict(n='Edge Slide', d='Edge Slide')
	SEQSLIDE = dict(n='Sequence Slide', d='Sequence Slide')
	GPENCIL_OPACITY = dict(n='Grease Pencil Opacity', d='Grease Pencil Opacity')
