
classes = {"CORE": [("ui.UILists", [("DecalLibsUIList", ""),
                                    ("SimpleDecalLibsUIList", ""),
                                    ("AtlasesUIList", ""),
                                    ("ExportAtlasesUIList", ""),
                                    ("AtlasChannelPackUIList", ""),
                                    ("TrimsUIList", ""),
                                    ("TrimMapsUIList", ""),
                                    ("AtlasTrimsUIList", "")]),
                    ("properties", [("DecalLibsCollection", ""),
                                    ("DecalScalesCollection", ""),
                                    ("ExcludeCollection", ""),
                                    ("PreBakePreviewMaterialsCollection", ""),
                                    ("TrimsCollection", ""),
                                    ("TrimMapsCollection", ""),
                                    ("AtlasesCollection", ""),
                                    ("AtlasChannelPackCollection", ""),
                                    ("PreAtlasMaterialsCollection", ""),
                                    ("PreJoinDecalsCollection", "")]),
                    ("preferences", [("DECALmachinePreferences", "")]),

                    ("ui.operators.call_operator", [("CallDecalOperator", "call_decal_operator")]),
                    ("ui.operators.call_menu", [("DecalLibraryVisibility", "decal_library_visibility")]),
                    ('ui.operators.draw', [('DrawDecalLabel', 'draw_decal_label')]),
                    ("ui.operators.folder", [("OpenInstantLocation", "open_instant_location"),
                                             ("OpenUserDecalLib", "open_user_decal_lib"),
                                             ("OpenFolder", "open_folder")]),
                    ("ui.operators.help", [("GetSupport", "get_decalmachine_support"),
                                           ("CoatInfo", "coat_info")]),
                    ('ui.operators.update', [('RemoveUpdate', 'remove_decalmachine_update'),
                                             ('UseFoundUpdate', 'use_decalmachine_update'),
                                             ('ReScanUpdates', 'rescan_decalmachine_updates')]),
                    ("ui.operators.assets", [("ResetDECALmachineAssetsLocation", "reset_decalmachine_assets_location"),
                                             ("QuarantineLibrary", "quarantine_asset_lib"),
                                             ("Declutter", "decclutter_assetspath")]),

                    ("ui.operators.libraries", [("Move", "move_decal_library"),
                                                ("Clear", "clear_decal_library"),
                                                ("Rename", "rename_decal_library"),
                                                ("Reload", "reload_decal_libraries"),
                                                ("Remove", "remove_decal_library")]),

                    ("ui.operators.trims", [("Add", "add_trim"),
                                            ("Remove", "remove_trim"),
                                            ("Duplicate", "duplicate_trim"),
                                            ("Draw", "draw_trim"),
                                            ("Align", "align_trim"),
                                            ("HideAll", "hide_all_trims"),
                                            ("ResetAtlasTrim", "reset_atlas_trim"),
                                            ("ScaleAtlasTrim", "scale_atlas_trim"),
                                            ("AlignAtlasTrim", "align_atlas_trim"),
                                            ("ToggleAtlasTrimSort", "toggle_atlas_trim_sort")]),
                    ("ui.operators.atlases", [("Move", "move_atlas"),
                                              ("Reload", "reload_atlases"),
                                              ("Rename", "rename_atlases"),
                                              ("Remove", "remove_atlas")]),
                    ("ui.operators.presets", [("LibraryVisibilityPreset", "decal_library_visibility_preset")]),

                    ("ui.operators.pil", [("InstallPIL", "install_pil"),
                                          ("InstallPILAdmin", "install_pil_admin"),
                                          ("EasyInstallPILAdmin", "easy_install_pil_admin"),
                                          ("PurgePIL", "purge_pil")]),
                    ("ui.operators.pack", [("PackImages", "pack_images"),
                                           ("UnpackImages", "unpack_images")]),
                    ("ui.operators.decal", [("SweepDecalBackups", "sweep_decal_backups")]),
                    ("properties", [("DecalSceneProperties", ""),
                                    ("DecalObjectProperties", ""),
                                    ("DecalMaterialProperties", ""),
                                    ("DecalImageProperties", ""),
                                    ("DecalCollectionProperties", "")])],

           "PIE_MENU": [("ui.pies", [("PieDecalMachine", "decal_machine")]),
                        ("ui.operators.scale", [("StoreIndividualDecalScale", "store_individual_decal_scale"),
                                                ("ClearIndividualDecalScale", "clear_individual_decal_scale")]),
                        ("ui.operators.set", [("Set", "set_default_property"),
                                              ("Reset", "reset_default_property")]),
                        ("ui.operators.call_pie", [("CallDecalPie", "call_decal_pie")])],

           "PANEL": [("ui.panels", [("PanelDECALmachine", "decal_machine"),
                                    ("PanelDecalCreation", "decal_creation"),
                                    ("PanelDecalExport", "decal_export"),
                                    ("PanelUpdateDecals", "update_decals"),
                                    ("PanelHelp", "help_decal_machine"),
                                    ("PanelMaterial", "material_decal_machine")]),
                     ("ui.operators.match_material", [("UpdateMatchMaterials", "update_match_materials")])],

           "GIZMO": [("ui.gizmos", [("GizmoGroupTrimSheet", "trimsheet"),
                                    ("GizmoGroupAtlas", "atlas")])],

           "INSERTREMOVE": [("operators.insert", [("Insert", "insert_decal"),
                                                  ("Remove", "remove_decal"),
                                                  ("QuickInsert", "quick_insert_decal"),
                                                  ("ClearInstant", "clear_instant"),
                                                  ("RemoveAllInstantDecals", "remove_all_instant_decals")])],
           "ADJUST": [("operators.adjust_decal", [("Adjust", "adjust_decal")])],
           "REAPPLY": [("operators.reapply", [("ReApply", "reapply_decal")])],
           "PROJECT": [("operators.project", [("Project", "project_decal"),
                                              ("UnShrinkwrap", "unshrinkwrap_decal")])],
           "SLICE": [("operators.slice", [("Slice", "slice_decal")]),
                     ("operators.gpanel", [("GPanel", "gpanel")]),
                     ("operators.epanel", [("EPanel", "epanel")])],
           "GETBACKUP": [("operators.backup", [("GetBackup", "get_backup_decal")])],
           "PANELCUT": [("operators.cut_panel", [("PanelCut", "panel_cut"),
                                                 ("RemoveMeshCuts", "remove_mesh_cuts")]),
                        ("operators.draw.draw_meshcut", [("DrawMeshCut", "draw_meshcut")])],

           "UNWRAP": [("operators.unwrap_panel", [("Unwrap", "panel_decal_unwrap")])],
           "MATCH": [("operators.match", [("Match", "match_material")])],
           "SELECT": [("operators.select", [("Select", "select_decals")])],

           "CREATE": [("operators.create", [("Create", "create_decal"),
                                            ("BatchCreate", "batch_create_decals"),
                                            ("LoadImages", "load_images"),
                                            ("ClearImages", "clear_images"),
                                            ("LoadFonts", "load_fonts"),
                                            ("ClearFonts", "clear_fonts"),
                                            ("AddDecalToLibrary", "add_decal_to_library"),
                                            ("UpdateDecalLibrary", "update_decal_library"),
                                            ("UpdateBlendFile", "update_blend_file"),
                                            ("BatchUpdate", "batch_update_decal_libraries")])],

           "BAKE": [("operators.bake", [("Bake", "bake_decals"),
                                        ("RestorePreBakePreviewMaterials", "restore_pre_bakepreview_materialsi")])],

           "TEXTURECOORDINATES": [("operators.texture_coordinates", [("InitGeneratedCoordinates", "init_generated_coordinates"),
                                                                     ("UVTransfer", "uv_transfer")])],

           "TRIMSHEET": [("operators.trimsheet", [("LoadTrimSheetTextures", "load_trimsheet_textures"),
                                                  ("ClearTrimSheetTextures", "clear_trimsheet_textures"),
                                                  ("InitTrimSheet", "init_trimsheet"),
                                                  ("DuplicateTrimSheet", "duplicate_trimsheet"),
                                                  ("ImportTrimSheet", "import_trimsheet"),
                                                  ("ClearTrimMap", "clear_trim_map"),
                                                  ("UpdateTrimMap", "update_trim_map"),
                                                  ("TrimSheet", "trimsheet"),
                                                  ("CreateTrimSheetLibrary", "create_trimsheet_library"),
                                                  ("RemoveInstantTrimSheet", "remove_instant_trim_sheet"),
                                                  ("InitTrimSheetMaterial", "init_trimsheet_mat"),
                                                  ("SetupSubsets", "setup_trimsheet_subsets")])],

           "TRIMCUT": [("operators.cut_trim", [("TrimCut", "trim_cut")])],

           "TRIMUNWRAP": [("operators.unwrap_trim", [("TrimUnwrap", "trim_unwrap")]),
                          ("operators.unwrap_trim_to_empty", [("TrimUnwrapToEmpty", "trmi_unwrap_to_empty")]),
                          ("operators.unwrap_quad", [("QuadUnwrap", "quad_unwrap")]),
                          ("operators.unwrap_box", [("BoxUnwrap", "box_unwrap")])],

           "TRIMADJUST": [("operators.adjust_trim", [("TrimAdjust", "trim_adjust")])],

           "ATLAS": [("operators.atlas", [("CreateAtlas", "create_atlas"),
                                          ("ImportAtlas", "import_atlas"),
                                          ("AddDecalsToAtlas", "add_decals_to_atlas"),
                                          ("RemoveDecalFromAtlas", "remove_decal_from_atlas"),
                                          ("RemoveInstantAtlas", "remove_instant_atlas"),
                                          ("StoreAtlas", "store_atlas"),
                                          ("UseAtlas", "use_atlas"),
                                          ("RestorePreAtlasDecalMaterials", "restore_preatlas_decal_materials"),
                                          ("AddAtlasChannelPack", "add_atlas_channel_pack"),
                                          ("RemoveAtlasChannelPack", "remove_atlas_channel_pack"),
                                          ("Export", "exort_atlas_decals")])],

           "MIRROR": [("operators.mirror_trim", [("MirrorTrim", "mirror_trim")])],

           "ALIGN": [("operators.align", [("AlignDecalToEdge", "align_decal_to_edge")])],

           "STITCH": [("operators.stitch", [("Stitch", "stitch")])],

           "JOIN": [("operators.join", [("Join", "join_decal"),
                                        ("JoinAtlased", "join_atlased_decals"),
                                        ("Split", "split_decal"),
                                        ("SplitAtlased", "split_atlased_decals")])],

           "OVERRIDE": [("operators.override", [("OverrideMaterials", "override_decal_materials")])],

           "UTILS": [("operators.utils", [("FixTexturePaths", "fix_decal_texture_paths"),
                                          ("Validate", "validate_decal"),
                                          ("ClearProps", "clear_decal_props"),
                                          ("RemoveOrphans", "remove_decal_orphans"),
                                          ("RestoreUserKeymapItems", "restore_decal_machine_user_keymap_items")])],

           "DEBUG": [("operators.debug", [("ReRenderThumbnails", "rerender_decal_thumbnails"),
                                          ("DECALmachineDebug", "decalmachine_debug"),
                                          ("UpdateAddNodesClamping", "update_add_nodes_clamping"),
                                          ("DECALmachineDebugToggle", "decalmachine_debug_toggle")])],
           }

keys = {"PIE_MENU": [{"label": "Object Mode", "keymap": "Object Mode", "idname": "machin3.call_decal_pie", "type": "D", "value": "PRESS", "properties": [("idname", "decal_machine")]},
                     {"label": "Edit Mode", "keymap": "Mesh", "idname": "machin3.call_decal_pie", "type": "D", "value": "PRESS", "properties": [("idname", "decal_machine")]},
                     {"label": "UV Editor", "keymap": "UV Editor", "idname": "machin3.call_decal_pie", "type": "D", "value": "PRESS", "properties": [("idname", "decal_machine")]}],

        "QUICK_INSERT": [{"label": "3D View", "keymap": "Object Mode", "idname": "machin3.call_decal_operator", "type": "D", "value": "PRESS", "ctrl": True, "properties": [("idname", "quick_insert_decal"), ("isinvoke", True)]}],
        "SELECT": [{"label": "3D View", "keymap": "Object Mode", "idname": "machin3.select_decals", "type": "LEFTMOUSE", "value": "DOUBLE_CLICK", "info": ["For multiple objects, double-click in the background", "Users of the 2.80/default Blender keymap and users selecting with RIGHTMOUSE: consider remapping this"]}],
        }
